//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//

/**
 * Calculator
 * 
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://c.b.a", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package a.b.c;
